### ISSUE TITLE
Merge with PSWinGlue?

### ISSUE THREAD

**Issue by unquietwiki** [ralish/PSWinVitals#4]
Hey @ralish : I just found https://github.com/ralish/PSWinGlue today, and then saw you had this up too. From an admin / engineering perspective, would it not be better to have these two packages together as one?

**Comment by ralish** [comment]
I get the rationale but would rather keep them separate for the time being. The reasons are two-fold:
1. `PSWinVitals` is quite narrowly focused on providing some useful system reporting, health checks, and maintenance functions. To that extent, it only exports three cmdlets. `PSWinGlue` is much more broadly focused on pretty much anything I think is a useful ad-hoc function subject to wider re-use.
2. `PSWinGlue` is frankly in need of some TLC as it's not at the same standard as `PSWinVitals`. That said, I hope to find the time to give it some attention soon and add a few things!
