### ISSUE TITLE
Separate public and private functions

### ISSUE THREAD

**Issue by jdhitsolutions** [ralish/PSWinVitals#7]
I'd like to suggest that you separate public and private functions in your module. You can either put all the public functions in one file and private in another or organize them in folders.  I think you'll find this easier to maintain the module, and it definitely makes things easier to test with Pester.

**Comment by ralish** [comment]
Adding Pester tests is definitely something I'd like to do, but I'm unclear on the benefit of what you're suggesting? PowerShell doesn't have any concept of public or private functions; modules do via the exported functions, and we use that here by only exporting the three functions which are the entry-points into the module functionality. I expect with Pester I'd be writing tests for the "private" functions as well.

This feels like it may be of some code organisation benefit, but the module is only ~1600 lines atm with the built-in documentation, so it's not quite at the point I feel where the cognitive complexity is high enough to bother yet. Is there a technical benefit I'm not appreciating regarding this suggestion?

**Comment by jdhitsolutions** [comment]
You are correct that there is no technical requirement. It comes down to ease of management and troubleshooting. I think most people find it easier to work with small files and monolithic ones. I also think that a well-organized module is also a great indicator of the quality of the code. If I see a detailed module structure, I can (usually) safely assume the author has some experience and pays attention to details which almost always carries over into the quality of their code.

So while there isn't a technical requirement, there is an intangible part of PowerShell scripting that I feel many people neglect. This is, of course, my opinion, but it is based on 16 years of PowerShell experience.

**Comment by ralish** [comment]
Thanks @jdhitsolutions. I've got no immediate plans to do this, but will keep it in mind based on future updates to the module. It feels like a logical step if the module grows much larger than it already is.
